version: "3.9"

volumes:
  react-dist:
  postgres_data:
  jenkins_home:

services:

  ############################
  # Frontend (React build)
  ############################
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - react-dist:/dist
    command: >
      sh -c "
      npm ci &&
      npm run build &&
      cp -r dist/. /dist
      "

  ############################
  # Backend (Django)
  ############################
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DB_NAME: mydb
      DB_USER: shawn
      DB_PASSWORD: shawn4823
      DB_HOST: db
      DB_PORT: 5432

  ############################
  # Database (PostgreSQL)
  ############################
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: shawn
      POSTGRES_PASSWORD: shawn4823
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ############################
  # Nginx (React + API Proxy)
  ############################
  nginx:
    build:
      context: ./nginx
    container_name: react-nginx
    ports:
      - "80:80"
    volumes:
      - react-dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  ############################
  # Jenkins (CI/CD)
  ############################
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always